import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Colors } from '@/constants/Colors';
import { useMission } from '@/hooks/useMission';
import { missionService } from '@/services/missionService';

export default function ConfirmMissionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const mission = useMission(id); const [code, setCode] = useState(''); const [error, setError] = useState('');
  const confirm = () => { try { missionService.confirmMission(mission.id, code); router.replace(`/mission/${mission.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Código inválido.'); } };
  return <SafeAreaView style={styles.safe}><View style={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} color={Colors.light.text} /><Text style={styles.backText}>Confirmação da missão</Text></Pressable><View style={styles.hero}><Ionicons name="shield-checkmark-outline" size={44} color={Colors.light.tint} /><Text style={styles.title}>Confirme a conclusão</Text><Text style={styles.copy}>Partilhe este código com o Nengue para confirmar que a missão foi concluída.</Text><Text style={styles.code}>{mission.confirmationCode ?? '------'}</Text><Text style={styles.caption}>Código de confirmação</Text></View><Text style={styles.label}>Código recebido do cliente</Text><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="000000" placeholderTextColor="#999" style={styles.input} /><Text style={styles.qr}>Mostrar QR Code</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={confirm} style={styles.button}><Text style={styles.buttonText}>Confirmar missão</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20 }, back: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 35 }, backText: { color: Colors.light.text, fontSize: 17, fontWeight: '700' }, hero: { backgroundColor: '#EAF0FF', alignItems: 'center', borderRadius: 20, padding: 26 }, title: { color: Colors.light.text, fontSize: 25, fontWeight: '800', marginTop: 16 }, copy: { color: Colors.light.icon, textAlign: 'center', lineHeight: 21, marginTop: 8 }, code: { color: Colors.light.tint, fontSize: 36, fontWeight: '800', letterSpacing: 7, marginTop: 25 }, caption: { color: Colors.light.icon, fontSize: 12, marginTop: 4 }, label: { color: Colors.light.text, fontWeight: '700', marginTop: 30, marginBottom: 8 }, input: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 12, height: 55, paddingHorizontal: 16, fontSize: 22, letterSpacing: 5, textAlign: 'center', color: Colors.light.text }, qr: { textAlign: 'center', color: Colors.light.tint, fontWeight: '700', marginTop: 18 }, error: { color: '#BA1A1A', textAlign: 'center', marginTop: 13 }, button: { backgroundColor: Colors.light.secondary, height: 54, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 25 }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' } });