import { checkpointDescriptions, checkpointLabels, CURRENT_CLIENT_ID, CURRENT_EXECUTOR_ID, missionTransitions } from '@/constants/mission';
import { createConfirmationToken, MissionConfirmationPayload } from '@/services/qrService';
import { calculateDistance, MISSION_ARRIVAL_RADIUS_METERS } from '@/services/locationService';
import { Mission, MissionStatus } from '@/types/mission';

const now = () => new Date().toISOString();
const seed = (status: MissionStatus, id: string, title: string, description: string, location: string, serviceAmount: number, purchaseAmount: number, scheduledAt: string, clientId = CURRENT_CLIENT_ID): Mission => ({ id, title, description, location, scheduledAt, serviceAmount, purchaseAmount, totalAmount: serviceAmount + purchaseAmount, clientId, status, createdAt: now(), executorId: status !== 'AVAILABLE' ? CURRENT_EXECUTOR_ID : undefined, checkpoints: [{ status: 'CREATED', timestamp: now(), description: checkpointDescriptions.CREATED }, ...(status !== 'CREATED' ? [{ status: 'AVAILABLE' as MissionStatus, timestamp: now(), description: checkpointDescriptions.AVAILABLE }] : []), ...(status === 'ACCEPTED' || status === 'IN_PROGRESS' || status === 'AWAITING_CONFIRMATION' || status === 'COMPLETED' ? [{ status: 'ACCEPTED' as MissionStatus, timestamp: now(), description: checkpointDescriptions.ACCEPTED }] : []), ...(status === 'IN_PROGRESS' || status === 'AWAITING_CONFIRMATION' || status === 'COMPLETED' ? [{ status: 'IN_PROGRESS' as MissionStatus, timestamp: now(), description: checkpointDescriptions.IN_PROGRESS }] : []), ...(status === 'AWAITING_CONFIRMATION' || status === 'COMPLETED' ? [{ status: 'AWAITING_CONFIRMATION' as MissionStatus, timestamp: now(), description: checkpointDescriptions.AWAITING_CONFIRMATION }] : []), ...(status === 'COMPLETED' ? [{ status: 'COMPLETED' as MissionStatus, timestamp: now(), description: checkpointDescriptions.COMPLETED }] : [])] });

let missions: Mission[] = [seed('AVAILABLE', 'gas-01', 'Comprar botija de gás', 'Comprar uma botija de gás de 12kg e entregar em casa.', 'Maianga, Luanda', 4500, 18000, 'Hoje, 15:00'), seed('IN_PROGRESS', 'docs-02', 'Levar documentos', 'Recolher o envelope e entregar no escritório.', 'Mutamba, Luanda', 3000, 0, 'Hoje, 16:00'), seed('COMPLETED', 'queue-03', 'Esperar numa fila', 'Guardar o lugar na fila do balcão de atendimento.', 'Alvalade, Luanda', 5000, 0, 'Ontem, 14:20')];
const listeners = new Set<() => void>();
const notify = () => listeners.forEach((listener) => listener());
const find = (id: string) => { const mission = missions.find((item) => item.id === id); if (!mission) throw new Error('Missão não encontrada.'); return mission; };
const transition = (mission: Mission, next: MissionStatus) => { if (!missionTransitions[mission.status].includes(next)) throw new Error(`Transição inválida: ${mission.status} para ${next}.`); mission.status = next; mission.checkpoints.push({ status: next, timestamp: now(), description: checkpointDescriptions[next] }); };

export const missionService = {
  subscribe(listener: () => void) { listeners.add(listener); return () => { listeners.delete(listener); }; },
  list() { return [...missions]; },
  get(id: string) { return find(id); },
  create(input: Pick<Mission, 'title' | 'description' | 'location' | 'scheduledAt' | 'serviceAmount' | 'purchaseAmount' | 'destinationLocation'>) { const mission = { ...input, id: `mission-${Date.now()}`, totalAmount: input.serviceAmount + input.purchaseAmount, clientId: CURRENT_CLIENT_ID, status: 'AVAILABLE' as MissionStatus, createdAt: now(), checkpoints: [{ status: 'CREATED' as MissionStatus, timestamp: now(), description: checkpointDescriptions.CREATED }, { status: 'AVAILABLE' as MissionStatus, timestamp: now(), description: checkpointDescriptions.AVAILABLE }] }; missions = [mission, ...missions]; notify(); return mission; },
  acceptMission(id: string, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.status !== 'AVAILABLE' || mission.executorId) throw new Error('Esta missão já foi atribuída a outro Nengue.'); mission.executorId = executorId; mission.acceptedAt = now(); transition(mission, 'ACCEPTED'); notify(); return mission; },
  startTravel(id: string, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.executorId !== executorId || mission.status !== 'ACCEPTED') throw new Error('Apenas o Nengue atribuído pode iniciar esta missão.'); mission.checkpoints.push({ status: 'ACCEPTED', timestamp: now(), description: 'O Nengue está a caminho.' }); notify(); return mission; },
  arriveAtMission(id: string, location: { latitude: number; longitude: number }, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.executorId !== executorId || mission.status !== 'ACCEPTED') throw new Error('Apenas o Nengue atribuído pode registar a chegada.'); if (!mission.destinationLocation) throw new Error('Esta missão não tem destino GPS definido.'); const distance = calculateDistance(location.latitude, location.longitude, mission.destinationLocation.latitude, mission.destinationLocation.longitude); if (distance > MISSION_ARRIVAL_RADIUS_METERS) throw new Error('Você ainda está distante do local da missão.'); mission.checkpoints.push({ status: 'ACCEPTED', timestamp: now(), description: 'O Nengue chegou ao local.' }); notify(); return mission; },
  startMission(id: string, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.executorId !== executorId) throw new Error('Apenas o Nengue atribuído pode avançar esta missão.'); mission.startedAt = now(); transition(mission, 'IN_PROGRESS'); notify(); return mission; },
  requestCompletion(id: string, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.executorId !== executorId) throw new Error('Apenas o Nengue atribuído pode finalizar esta missão.'); mission.confirmationCode = String(Math.floor(100000 + Math.random() * 900000)); mission.confirmationToken = createConfirmationToken(mission.id); mission.confirmationCodeUsed = false; transition(mission, 'AWAITING_CONFIRMATION'); notify(); return mission; },
  confirmMission(id: string, code: string, clientId = CURRENT_CLIENT_ID) { const mission = find(id); if (mission.clientId !== clientId) throw new Error('Esta missão não pertence a este cliente.'); if (mission.executorId === clientId) throw new Error('O executor não pode confirmar a própria missão.'); if (mission.status !== 'AWAITING_CONFIRMATION' || mission.confirmationCodeUsed || mission.confirmationCode !== code) throw new Error('Código de confirmação inválido.'); mission.confirmationCodeUsed = true; mission.confirmationToken = undefined; mission.completedAt = now(); transition(mission, 'COMPLETED'); notify(); return mission; },
  confirmMissionByQr(payload: MissionConfirmationPayload, executorId = CURRENT_EXECUTOR_ID) { const mission = find(payload.missionId); if (mission.executorId !== executorId) throw new Error('Este QR não pertence à sua missão.'); if (mission.status !== 'AWAITING_CONFIRMATION' || mission.confirmationCodeUsed || mission.confirmationToken !== payload.confirmationToken) throw new Error('QR de confirmação inválido.'); mission.confirmationCodeUsed = true; mission.confirmationToken = undefined; mission.completedAt = now(); transition(mission, 'COMPLETED'); notify(); return mission; },
  setExecutorLocation(id: string, location: { latitude: number; longitude: number; accuracy?: number; updatedAt: string }, executorId = CURRENT_EXECUTOR_ID) { const mission = find(id); if (mission.executorId !== executorId) throw new Error('Apenas o Nengue atribuído pode enviar localização.'); mission.executorLocation = location; notify(); return mission; },
  cancelMission(id: string, actorId: string) { const mission = find(id); if (mission.clientId !== actorId && mission.executorId !== actorId) throw new Error('Sem permissão para cancelar esta missão.'); transition(mission, 'CANCELLED'); notify(); return mission; },
};

export { checkpointLabels };