import { Colors } from '@/constants/Colors';
import { missionService } from '@/services/missionService';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function CreateMissionScreen() {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [location, setLocation] = useState(''); const [scheduledAt, setScheduledAt] = useState(''); const [purchaseAmount, setPurchaseAmount] = useState('0'); const [serviceAmount, setServiceAmount] = useState(''); const [error, setError] = useState('');
  const publish = async () => { if (!title || !description || !location || !serviceAmount) { setError('Preencha os campos obrigatórios.'); return; } try { setError(''); await missionService.create({ title, description, location, scheduledAt: scheduledAt || 'A combinar', serviceAmount: Number(serviceAmount), purchaseAmount: Number(purchaseAmount) || 0 }); router.replace('/'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível criar a missão.'); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={Colors.light.text} /></Pressable><Text style={styles.topTitle}>Nova missão</Text><View style={{ width: 24 }} /></View><Text style={styles.title}>Diga-nos do que precisa</Text><Text style={styles.copy}>Descreva livremente a tarefa. Um Nengue tratará do resto.</Text><Field label="O que precisa que façamos?" value={title} onChangeText={setTitle} placeholder="Ex.: Comprar pão" /><Field label="Detalhes da missão" value={description} onChangeText={setDescription} placeholder="Explique o que precisa que seja feito" multiline /><Field label="Onde?" value={location} onChangeText={setLocation} placeholder="Ex.: Talatona, Luanda" /><Field label="Quando?" value={scheduledAt} onChangeText={setScheduledAt} placeholder="Ex.: Hoje às 15:00" /><Field label="Valor estimado das compras (Kz)" value={purchaseAmount} onChangeText={setPurchaseAmount} placeholder="0" keyboardType="numeric" /><Field label="Quanto oferece pelo serviço? (Kz)" value={serviceAmount} onChangeText={setServiceAmount} placeholder="0" keyboardType="numeric" /><View style={styles.summary}><Text style={styles.summaryTitle}>Resumo</Text><Line label="Valor do serviço" value={Number(serviceAmount) || 0} /><Line label="Compras estimadas" value={Number(purchaseAmount) || 0} /><View style={styles.totalLine}><Text style={styles.totalLabel}>Total estimado</Text><Text style={styles.total}>{((Number(serviceAmount) || 0) + (Number(purchaseAmount) || 0)).toLocaleString('pt-AO')} Kz</Text></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={() => void publish()} style={styles.button}><Text style={styles.buttonText}>Publicar Missão</Text><Ionicons name="arrow-forward" size={20} color="#FFF" /></Pressable></ScrollView></SafeAreaView>;
}
function Field({ label, multiline, ...props }: { label: string; multiline?: boolean; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: 'numeric' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} placeholderTextColor="#999" style={[styles.input, multiline && styles.multiline]} /></View>; }
function Line({ label, value }: { label: string; value: number }) { return <View style={styles.line}><Text style={styles.lineLabel}>{label}</Text><Text style={styles.lineValue}>{value.toLocaleString('pt-AO')} Kz</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20, paddingBottom: 40 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32 }, topTitle: { fontSize: 16, fontWeight: '700', color: Colors.light.text }, title: { fontSize: 30, lineHeight: 36, fontWeight: '800', color: Colors.light.text }, copy: { color: Colors.light.icon, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 12 }, field: { marginTop: 17 }, label: { color: Colors.light.text, fontWeight: '700', fontSize: 14, marginBottom: 8 }, input: { backgroundColor: '#FFF', borderColor: '#E5E2E1', borderWidth: 1, borderRadius: 12, minHeight: 52, paddingHorizontal: 15, color: Colors.light.text, fontSize: 15 }, multiline: { minHeight: 100, paddingTop: 14, textAlignVertical: 'top' }, summary: { backgroundColor: '#EAF0FF', borderRadius: 14, padding: 16, marginTop: 25 }, summaryTitle: { color: Colors.light.tint, fontWeight: '800', fontSize: 17, marginBottom: 12 }, line: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 4 }, lineLabel: { color: Colors.light.icon }, lineValue: { color: Colors.light.text, fontWeight: '600' }, totalLine: { borderTopWidth: 1, borderTopColor: '#C3D2F5', marginTop: 9, paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' }, totalLabel: { color: Colors.light.text, fontWeight: '800' }, total: { color: Colors.light.tint, fontWeight: '800', fontSize: 17 }, error: { color: '#BA1A1A', marginTop: 12 }, button: { height: 54, marginTop: 24, backgroundColor: Colors.light.secondary, borderRadius: 13, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10 }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' } });