import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Colors } from '@/constants/Colors';

const labels = ['', 'Muito Fraco', 'Fraco', 'Razoável', 'Muito Bom', 'Excelente!'];
const chips = ['Pontualidade', 'Educação', 'Rapidez'];
export default function RatingScreen() {
  const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [sent, setSent] = useState(false);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.nav}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={Colors.light.text} /></Pressable><Text style={styles.logo}>De Lhe Mandar</Text><View style={{ width: 24 }} /></View><View style={styles.center}><Text style={styles.title}>Como foi a sua experiência?</Text><Text style={styles.copy}>Avalie o serviço prestado para nos ajudar a melhorar.</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>MA</Text><View style={styles.verified}><Ionicons name="checkmark" size={12} color="#FFF" /></View></View><Text style={styles.name}>Marcos A.</Text><Text style={styles.role}>Executor de Missão</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((value) => <Pressable key={value} onPress={() => setRating(value)}><Ionicons name={value <= rating ? 'star' : 'star-outline'} size={39} color={value <= rating ? Colors.light.secondary : '#C3C6D5'} /></Pressable>)}</View><Text style={styles.ratingLabel}>{labels[rating]}</Text></View></View><Text style={styles.label}>O que correu bem?</Text><TextInput value={comment} onChangeText={setComment} multiline numberOfLines={4} placeholder="Escreva aqui o seu comentário..." placeholderTextColor="#999" style={styles.textarea} /><View style={styles.chips}>{chips.map((chip) => <Pressable key={chip} onPress={() => setSelected((current) => current.includes(chip) ? current.filter((item) => item !== chip) : [...current, chip])} style={[styles.chip, selected.includes(chip) && styles.selectedChip]}><Text style={[styles.chipText, selected.includes(chip) && styles.selectedText]}>{chip}</Text></Pressable>)}</View><Pressable onPress={() => setSent(true)} style={styles.button}><Text style={styles.buttonText}>Submeter Avaliação</Text></Pressable><Pressable onPress={() => router.back()}><Text style={styles.skip}>Saltar por agora</Text></Pressable>{sent && <View style={styles.toast}><Ionicons name="checkmark-circle" size={20} color={Colors.light.secondary} /><Text style={styles.toastText}>Obrigado pelo seu feedback!</Text></View>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20, paddingBottom: 40 }, nav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32 }, logo: { color: Colors.light.tint, fontSize: 17, fontWeight: '800' }, center: { alignItems: 'center' }, title: { color: Colors.light.text, fontSize: 27, lineHeight: 34, fontWeight: '800', textAlign: 'center' }, copy: { color: Colors.light.icon, fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 8 }, profile: { width: '100%', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 20, borderWidth: 1, borderColor: '#E5E2E1', padding: 24, marginTop: 24, marginBottom: 22 }, avatar: { width: 86, height: 86, borderRadius: 43, backgroundColor: '#D9E2FF', alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: '#FFF' }, avatarText: { color: Colors.light.tint, fontSize: 25, fontWeight: '800' }, verified: { position: 'absolute', right: -2, bottom: 0, backgroundColor: Colors.light.tint, width: 23, height: 23, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, name: { color: Colors.light.text, fontSize: 20, fontWeight: '800', marginTop: 12 }, role: { color: Colors.light.icon, fontSize: 13, marginTop: 3, marginBottom: 17 }, stars: { flexDirection: 'row', gap: 3 }, ratingLabel: { height: 20, color: Colors.light.secondary, fontWeight: '700', marginTop: 6 }, label: { color: Colors.light.text, fontWeight: '700', fontSize: 14, marginBottom: 8 }, textarea: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 12, minHeight: 110, padding: 14, textAlignVertical: 'top', color: Colors.light.text, fontSize: 15 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 14 }, chip: { paddingHorizontal: 15, paddingVertical: 10, borderRadius: 20, borderWidth: 1, borderColor: '#C3C6D5' }, selectedChip: { backgroundColor: Colors.light.tint, borderColor: Colors.light.tint }, chipText: { color: Colors.light.text, fontSize: 13, fontWeight: '600' }, selectedText: { color: '#FFF' }, button: { height: 54, backgroundColor: Colors.light.secondary, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' }, skip: { textAlign: 'center', color: Colors.light.icon, marginTop: 17, textDecorationLine: 'underline' }, toast: { position: 'absolute', bottom: 15, alignSelf: 'center', backgroundColor: '#313030', borderRadius: 22, paddingHorizontal: 18, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, toastText: { color: '#FFF', fontWeight: '600' } });