import { MissionMap } from '@/components/MissionMap';
import { MissionPriceBreakdown } from '@/components/MissionPriceBreakdown';
import { MissionQRCode } from '@/components/MissionQRCode';
import { MissionTimeline } from '@/components/MissionTimeline';
import { Colors } from '@/constants/Colors';
import { useMission } from '@/hooks/useMission';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text } from 'react-native';
export default function ClientMissionScreen() { const { id = 'docs-02' } = useLocalSearchParams<{ id: string }>(); const mission = useMission(id); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{mission.title}</Text><Text style={styles.location}>{mission.location} · {mission.scheduledAt}</Text><Text style={styles.description}>{mission.description}</Text><MissionMap destination={mission.destinationLocation} executorLocation={mission.executorLocation} status={mission.status} /><MissionPriceBreakdown serviceAmount={mission.serviceAmount} purchaseAmount={mission.purchaseAmount} /><Text style={styles.section}>Acompanhe a sua missão</Text><MissionTimeline mission={mission} />{mission.status === 'AWAITING_CONFIRMATION' && <><MissionQRCode mission={mission} /><Pressable style={styles.button} onPress={() => router.push(`/(client)/mission/confirmation?id=${mission.id}`)}><Text style={styles.buttonText}>Ver confirmação</Text></Pressable></>}{mission.status === 'COMPLETED' && <Pressable style={styles.button} onPress={() => router.push({ pathname: '/(client)/rating', params: { missionId: mission.id, executorId: mission.executorId ?? '' } })}><Text style={styles.buttonText}>Avaliar Nengue</Text></Pressable>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20, paddingTop: 60 }, title: { color: Colors.light.text, fontSize: 29, fontWeight: '800' }, location: { color: Colors.light.icon, marginTop: 8 }, description: { color: Colors.light.icon, fontSize: 16, lineHeight: 24, marginVertical: 22 }, section: { color: Colors.light.text, fontSize: 20, fontWeight: '800', marginTop: 30, marginBottom: 18 }, button: { backgroundColor: Colors.light.secondary, height: 54, borderRadius: 13, justifyContent: 'center', alignItems: 'center', marginTop: 20 }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' } });