import { CameraView, useCameraPermissions } from 'expo-camera';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { parseConfirmationPayload } from '@/services/qrService';
import { Colors } from '@/constants/Colors';

type ScannerState = 'REQUESTING_PERMISSION' | 'READY' | 'SCANNING' | 'SUCCESS' | 'ERROR';
export function QRCodeScanner({ onToken, onOtpFallback }: { onToken: (value: string) => void; onOtpFallback: () => void }) {
  const [permission, requestPermission] = useCameraPermissions(); const [state, setState] = useState<ScannerState>(permission?.granted ? 'READY' : 'REQUESTING_PERMISSION'); const [error, setError] = useState('');
  if (!permission?.granted) return <View style={styles.center}><Text style={styles.title}>Precisamos da câmera para confirmar esta missão.</Text><Pressable style={styles.button} onPress={async () => { setState('REQUESTING_PERMISSION'); const result = await requestPermission(); setState(result.granted ? 'READY' : 'ERROR'); }}><Text style={styles.buttonText}>Permitir câmera</Text></Pressable><Pressable onPress={onOtpFallback}><Text style={styles.link}>Usar código OTP</Text></Pressable>{state === 'ERROR' && <Text style={styles.error}>Acesso à câmera foi negado.</Text>}</View>;
  return <View style={styles.wrapper}><CameraView style={styles.camera} facing="back" barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onBarcodeScanned={state === 'SCANNING' ? ({ data }) => { const payload = parseConfirmationPayload(data); if (!payload) { setError('QR inválido para esta missão.'); setState('ERROR'); return; } setState('SUCCESS'); onToken(JSON.stringify(payload)); } : undefined} /><View style={styles.overlay}><Text style={styles.scanText}>{state === 'SUCCESS' ? 'QR lido com sucesso' : 'Aponte para o QR Code'}</Text></View><Pressable style={styles.scanButton} onPress={() => { setError(''); setState('SCANNING'); }}><Text style={styles.buttonText}>Digitalizar QR</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={onOtpFallback}><Text style={styles.link}>Usar código OTP</Text></Pressable></View>;
}
const styles = StyleSheet.create({ wrapper: { overflow: 'hidden', borderRadius: 16, backgroundColor: '#1C1B1B', paddingBottom: 16 }, camera: { height: 280 }, overlay: { position: 'absolute', top: 18, left: 0, right: 0, alignItems: 'center' }, scanText: { color: '#FFF', fontWeight: '700' }, center: { alignItems: 'center', backgroundColor: '#FFF', borderRadius: 16, padding: 25 }, title: { color: Colors.light.text, fontSize: 16, lineHeight: 22, textAlign: 'center' }, button: { backgroundColor: Colors.light.tint, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 13, marginTop: 18 }, scanButton: { alignSelf: 'center', backgroundColor: Colors.light.secondary, borderRadius: 12, paddingHorizontal: 22, paddingVertical: 13, marginTop: 14 }, buttonText: { color: '#FFF', fontWeight: '800' }, link: { color: Colors.light.tint, fontWeight: '700', marginTop: 17 }, error: { color: '#FFB4AB', marginTop: 12, textAlign: 'center' } });