import { MissionTimeline } from '@/components/MissionTimeline';
import { Colors } from '@/constants/Colors';
import { useMission } from '@/hooks/useMission';
import { missionService } from '@/services/missionService';
import { statusLabels } from '@/types/mission';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function MissionDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const mission = useMission(id); const [error, setError] = useState('');
  const action = async (callback: () => Promise<void>) => { try { setError(''); await callback(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível atualizar a missão.'); } };
  const button: { label: string; action: () => Promise<void> } | null = mission.status === 'AVAILABLE' ? { label: 'Aceitar missão', action: async () => { await missionService.acceptMission(mission.id); } } : mission.status === 'ACCEPTED' ? { label: 'Estou a caminho', action: async () => { await missionService.startMission(mission.id); } } : mission.status === 'IN_PROGRESS' ? { label: 'Finalizar missão', action: async () => { await missionService.requestCompletion(mission.id); router.push(`/mission/confirm/${mission.id}`); } } : null;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} color={Colors.light.text} /><Text style={styles.backText}>Detalhes da missão</Text></Pressable><View style={styles.heading}><Text style={styles.title}>{mission.title}</Text><View style={styles.status}><Text style={styles.statusText}>{statusLabels[mission.status]}</Text></View></View><Text style={styles.description}>{mission.description}</Text><View style={styles.info}><View><Text style={styles.label}>LOCALIZAÇÃO</Text><Text style={styles.value}>{mission.location}</Text></View><View><Text style={styles.label}>HORÁRIO</Text><Text style={styles.value}>{mission.scheduledAt}</Text></View></View><View style={styles.money}><Text style={styles.label}>TOTAL ESTIMADO</Text><Text style={styles.total}>{mission.totalAmount.toLocaleString('pt-AO')} Kz</Text><Text style={styles.moneyDetail}>Serviço {mission.serviceAmount.toLocaleString('pt-AO')} Kz + Compras {mission.purchaseAmount.toLocaleString('pt-AO')} Kz</Text></View><Text style={styles.section}>Progresso da missão</Text><MissionTimeline mission={mission} />{error ? <Text style={styles.error}>{error}</Text> : null}{button && <Pressable style={styles.button} onPress={() => void action(button.action)}><Text style={styles.buttonText}>{button.label}</Text></Pressable>}{mission.status === 'AWAITING_CONFIRMATION' && <Pressable style={styles.outline} onPress={() => router.push(`/mission/confirm/${mission.id}`)}><Text style={styles.outlineText}>Abrir confirmação</Text></Pressable>}{mission.status === 'COMPLETED' && <Pressable style={styles.outline} onPress={() => router.push({ pathname: '/rating', params: { missionId: mission.id, executorId: mission.executorId ?? '' } })}><Text style={styles.outlineText}>Avaliar experiência</Text></Pressable>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20, paddingBottom: 40 }, back: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 30 }, backText: { fontSize: 16, fontWeight: '700', color: Colors.light.text }, heading: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, alignItems: 'flex-start' }, title: { fontSize: 29, lineHeight: 35, fontWeight: '800', color: Colors.light.text, flex: 1 }, status: { backgroundColor: '#FFF1E7', borderRadius: 18, paddingHorizontal: 10, paddingVertical: 7 }, statusText: { color: '#964900', fontSize: 11, fontWeight: '700' }, description: { color: Colors.light.icon, fontSize: 16, lineHeight: 24, marginTop: 12 }, info: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 14, padding: 17, marginTop: 22, justifyContent: 'space-between' }, label: { color: Colors.light.icon, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, value: { color: Colors.light.text, fontSize: 15, fontWeight: '700', marginTop: 6 }, money: { backgroundColor: '#EAF0FF', borderRadius: 14, padding: 17, marginTop: 12 }, total: { color: Colors.light.tint, fontWeight: '800', fontSize: 25, marginTop: 5 }, moneyDetail: { color: Colors.light.icon, marginTop: 5, fontSize: 12 }, section: { color: Colors.light.text, fontSize: 20, fontWeight: '800', marginTop: 30, marginBottom: 18 }, error: { color: '#BA1A1A', marginTop: 8 }, button: { height: 54, backgroundColor: Colors.light.secondary, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' }, outline: { height: 54, borderWidth: 1, borderColor: Colors.light.tint, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, outlineText: { color: Colors.light.tint, fontSize: 16, fontWeight: '800' } });