import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { MissionCard } from '@/components/MissionCard';
import { Colors } from '@/constants/Colors';
import { useMissions } from '@/hooks/useMission';

export default function HomeScreen() {
  const activeMissions = useMissions().filter((mission) => mission.status !== 'COMPLETED');
  return <SafeAreaView style={styles.safe}><FlatList data={activeMissions} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.kicker}>BEM-VINDO DE VOLTA, COTA</Text><Text style={styles.logo}>De Lhe Mandar</Text></View><Pressable onPress={() => router.push('/notifications')} style={styles.bell}><Ionicons name="notifications-outline" size={22} color={Colors.light.text} /><View style={styles.badge} /></Pressable></View><View style={styles.hero}><Text style={styles.heroTitle}>O que precisa que façamos por si hoje?</Text><Text style={styles.heroCopy}>Delegue uma tarefa. Nós tratamos do resto.</Text><Pressable onPress={() => router.push('/create-mission')} style={styles.primary}><Ionicons name="add" size={21} color="#FFF" /><Text style={styles.primaryText}>Criar Missão</Text></Pressable></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Missões Ativas</Text><Pressable onPress={() => router.push('/history')}><Text style={styles.link}>Ver todas</Text></Pressable></View></>} renderItem={({ item }) => <MissionCard mission={item} onPress={() => router.push(`/mission/${item.id}`)} />} ListFooterComponent={<View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Acesso rápido</Text></View><View style={styles.quickRow}><Pressable style={styles.quick} onPress={() => router.push('/available-missions')}><Ionicons name="compass-outline" size={22} color={Colors.light.tint} /><Text style={styles.quickText}>Missões disponíveis</Text></Pressable><Pressable style={styles.quick} onPress={() => router.push('/profile')}><Ionicons name="person-outline" size={22} color={Colors.light.secondary} /><Text style={styles.quickText}>Meu perfil</Text></Pressable></View></View>} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 20, paddingBottom: 28 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, kicker: { color: Colors.light.icon, fontSize: 11, fontWeight: '700', letterSpacing: 1 }, logo: { color: Colors.light.tint, fontSize: 22, fontWeight: '800', marginTop: 3 }, bell: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E2E1' }, badge: { width: 7, height: 7, borderRadius: 4, backgroundColor: Colors.light.secondary, position: 'absolute', right: 10, top: 9 }, hero: { backgroundColor: Colors.light.tint, borderRadius: 20, padding: 22, marginBottom: 28 }, heroTitle: { color: '#FFF', fontSize: 25, lineHeight: 31, fontWeight: '800', maxWidth: 290 }, heroCopy: { color: '#D9E2FF', fontSize: 15, marginTop: 8, marginBottom: 20 }, primary: { backgroundColor: Colors.light.secondary, borderRadius: 12, height: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryText: { color: '#FFF', fontSize: 16, fontWeight: '700' }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 13 }, sectionTitle: { color: Colors.light.text, fontSize: 20, fontWeight: '800' }, link: { color: Colors.light.tint, fontSize: 13, fontWeight: '700' }, quickRow: { flexDirection: 'row', gap: 10 }, quick: { flex: 1, backgroundColor: '#FFF', borderRadius: 14, padding: 16, borderWidth: 1, borderColor: '#E5E2E1' }, quickText: { color: Colors.light.text, fontWeight: '700', fontSize: 13, marginTop: 10 } });