import { Colors } from '@/constants/Colors';
import { sessionService } from '@/services/sessionService';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function LoginScreen() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<'CLIENT' | 'EXECUTOR'>('CLIENT'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const enter = async () => { try { setLoading(true); setError(''); await sessionService.signIn(role, email.trim(), password); router.replace(role === 'CLIENT' ? '/(client)/home' : '/(executor)/dashboard'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível entrar.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.logo}>De Lhe Mandar</Text><Text style={styles.title}>Entre na sua conta</Text><Text style={styles.copy}>Venda tempo, não entregas.</Text><View style={styles.roles}><Pressable onPress={() => setRole('CLIENT')} style={[styles.role, role === 'CLIENT' && styles.roleSelected]}><Text style={styles.roleText}>Cota</Text></Pressable><Pressable onPress={() => setRole('EXECUTOR')} style={[styles.role, role === 'EXECUTOR' && styles.roleSelected]}><Text style={styles.roleText}>Nengue</Text></Pressable></View><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#999" style={styles.input} /><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Palavra-passe" placeholderTextColor="#999" style={styles.input} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={styles.client} onPress={() => void enter()} disabled={loading}><Text style={styles.buttonText}>{loading ? 'A entrar...' : 'Entrar'}</Text></Pressable><Pressable onPress={() => router.push('/(auth)/register')}><Text style={styles.link}>Criar uma conta</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8' }, content: { padding: 24, paddingTop: 90 }, logo: { color: Colors.light.tint, fontSize: 24, fontWeight: '800' }, title: { color: Colors.light.text, fontSize: 31, fontWeight: '800', marginTop: 65 }, copy: { color: Colors.light.icon, fontSize: 16, marginTop: 8, marginBottom: 25 }, roles: { flexDirection: 'row', gap: 10, marginBottom: 13 }, role: { flex: 1, height: 42, borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, roleSelected: { backgroundColor: '#EAF0FF', borderColor: Colors.light.tint }, roleText: { color: Colors.light.text, fontWeight: '700' }, input: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 13, height: 54, paddingHorizontal: 16, marginBottom: 12, color: Colors.light.text }, error: { color: '#BA1A1A', marginBottom: 12 }, client: { backgroundColor: Colors.light.tint, height: 56, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFF', fontSize: 16, fontWeight: '800' }, link: { color: Colors.light.tint, textAlign: 'center', marginTop: 28, fontWeight: '700' } });
