import { Colors } from '@/constants/Colors';
import { sessionService } from '@/services/sessionService';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput } from 'react-native';

export default function RegisterScreen() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<'CLIENT' | 'EXECUTOR'>('CLIENT'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const register = async () => { try { setLoading(true); setError(''); const session = await sessionService.signUp(email.trim(), password, name.trim(), role); router.replace(session.role === 'CLIENT' ? '/(client)/home' : '/(executor)/dashboard'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível criar a conta.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><Text style={styles.title}>Crie a sua conta</Text><Text style={styles.copy}>Escolha como quer usar o De Lhe Mandar.</Text><TextInput value={name} onChangeText={setName} placeholder="Nome" placeholderTextColor="#999" style={styles.input} /><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#999" style={styles.input} /><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Palavra-passe" placeholderTextColor="#999" style={styles.input} /><Pressable onPress={() => setRole('CLIENT')} style={[styles.role, role === 'CLIENT' && styles.selected]}><Text style={styles.roleText}>Criar como Cota</Text></Pressable><Pressable onPress={() => setRole('EXECUTOR')} style={[styles.role, role === 'EXECUTOR' && styles.selected]}><Text style={styles.roleText}>Criar como Nengue</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={styles.button} onPress={() => void register()} disabled={loading}><Text style={styles.buttonText}>{loading ? 'A criar...' : 'Continuar'}</Text></Pressable></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FCF9F8', padding: 24, paddingTop: 100 }, title: { color: Colors.light.text, fontSize: 30, fontWeight: '800' }, copy: { color: Colors.light.icon, marginTop: 8, fontSize: 16, marginBottom: 22 }, input: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 13, height: 54, paddingHorizontal: 16, marginBottom: 12, color: Colors.light.text }, role: { height: 48, borderWidth: 1, borderColor: '#E5E2E1', borderRadius: 13, justifyContent: 'center', alignItems: 'center', marginTop: 8 }, selected: { backgroundColor: '#EAF0FF', borderColor: Colors.light.tint }, roleText: { color: Colors.light.text, fontWeight: '700' }, error: { color: '#BA1A1A', marginTop: 14 }, button: { height: 55, backgroundColor: Colors.light.secondary, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, buttonText: { color: '#FFF', fontWeight: '800', fontSize: 16 } });
